### ISSUE TITLE
Common metadata v2.8 schema missing VersionIntent

### ISSUE THREAD

**Issue by plondino** [MovieLabs/mddf#3]
The md-v2.8.xsd in the library is missing the VersionIntent declaration:

<xs:element name="VersionIntent" type="md:VersionIntent-type" minOccurs="0"/>

The schema in the library should match the latest on the web site.  This is affecting the online validation as well.

**Comment by ljlevin** [comment]
I'm going to consider this closed since the problem is corrected in v2.9. The only issue would be if somebody at some point explicitly tries to validate a file based on md-v2.8 AND alse decides to incorporate the optional VersionIntent element.
