### ISSUE TITLE
The unit tests for mddf-lib fail because of missing 'tmp' folder

### ISSUE THREAD

**Issue by plondino** [MovieLabs/mddf#5]
If you try to compile the code on a clean checkout using Maven, many unit tests fail with the following errror:

`java.io.FileNotFoundException: C:\code\java\mddf\mddf-lib\.\test\tmp\Avails_noErrors_v2.3.xml_v1.7.3.xlsx (The system cannot find the path specified)`

Creating the directory allows all tests to pass. It's possible this directory is just not getting checked in because Git ignores empty folders (a workaround is adding a .gitignore in the folder, see: https://stackoverflow.com/questions/115983/how-can-i-add-an-empty-directory-to-a-git-repository).  Alternately, the tests should create this directory and clean up after.

**Comment by ljlevin** [comment]
The JUnit tests dealing with the translation of an Avails from one encoding to another (i.e., XML to/from XLSX) are using this as a working directory. I think the best fix will be your 2nd suggestion: create the directory then clean-up on completion.

**Comment by plondino** [comment]
This has been fixed in the latest release.  The only issue is that while each test deletes the tempdir before running, the last test run leaves something in the temp directory.  This isn't a huge deal, but it might make sense to add it to the .gitignore file to avoid spurious changed files in Git.

**Comment by ljlevin** [comment]
.gitignore has been updated so I'm going to mark this as closed.
